version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aws-billing-backend-prod
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=false
      - DEFAULT_AWS_REGION=us-east-1
      - ALLOWED_ORIGINS=*
    volumes:
      - backend_logs:/app/logs
      - backend_data:/app/data
    networks:
      - aws-billing-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aws-billing-frontend-prod
    ports:
      - "${FRONTEND_PORT:-80}:3000"
    environment:
      - REACT_APP_API_URL=/api
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - aws-billing-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  aws-billing-network:
    driver: bridge

volumes:
  backend_data:
    driver: local
  backend_logs:
    driver: local